/** Backend endpoint paths (relative to VITE_API_BASE_URL). */
export const API_ENDPOINTS = {
  accounts: "/accounts",
  account: (id: string) => `/accounts/${id}`,
  transactions: "/transactions",
  transaction: (id: string) => `/transactions/${id}`,
  statements: "/statements",
  statement: (id: string) => `/statements/${id}`,
  dashboard: "/dashboard",
  dashboardGoal: "/dashboard/goal",
  budget: "/budget",
  categories: "/categories",
  budgetStarterTemplates: "/budget/starter-templates",
  savingsProgress: "/budget/savings-progress",
  goal: "/goal",
  usersMe: "/users/me",
  authSignup: "/auth/signup",
  authLogin: "/auth/login",
  authRefresh: "/auth/refresh",
  authLogout: "/auth/logout",
  adminAuthLogin: "/admin/auth/login",
  adminCategories: "/admin/categories",
  adminCategory: (id: string) => `/admin/categories/${id}`,
  adminProducts: "/admin/products",
  adminProduct: (id: string) => `/admin/products/${id}`,
  adminFeedback: "/admin/feedback",
  adminIssues: "/admin/issues",
  adminIssue: (id: string) => `/admin/issues/${id}`,
} as const;
