/** Backend endpoint paths (relative to VITE_API_BASE_URL). */
export const API_ENDPOINTS = {
  accounts: "/accounts",
  account: (id: string) => `/accounts/${id}`,
  transactions: "/transactions",
  transaction: (id: string) => `/transactions/${id}`,
  statements: "/statements",
  statement: (id: string) => `/statements/${id}`,
  statementOcrResult: (id: string) => `/statements/${id}/ocr-result`,
  statementOcrArtifactDownload: (id: string) => `/statements/${id}/ocr-result/download`,
  dashboard: "/dashboard",
  dashboardGoal: "/dashboard/goal",
  budget: "/budget",
  categories: "/categories",
  budgetStarterTemplates: "/budget/starter-templates",
  budgetHistory: "/budget/history",
  budgetProgress: "/budget/progress",
  savingsProgress: "/budget/savings-progress",
  goal: "/goal",
  usersMe: "/users/me",
  usersMeConsent: "/users/me/consent",
  usersMeConsentRevoke: (id: string) => `/users/me/consent/${id}`,
  usersMePreferences: "/users/me/preferences",
  authSignup: "/auth/signup",
  authLogin: "/auth/login",
  authRefresh: "/auth/refresh",
  authLogout: "/auth/logout",
  authVerifyEmailRequest: "/auth/verify-email/request",
  authVerifyEmailConfirm: "/auth/verify-email/confirm",
  authPasswordResetRequest: "/auth/password-reset/request",
  authPasswordResetConfirm: "/auth/password-reset/confirm",
  authBankLoginInitiate: "/auth/bank-login/initiate",
  authBankLoginCallback: "/auth/bank-login/callback",
  bankConnections: "/bank-connections",
  bankConnectionCallback: (id: string) => `/bank-connections/${id}/callback`,
  adminAuthLogin: "/admin/auth/login",
  adminCategories: "/admin/categories",
  adminCategory: (id: string) => `/admin/categories/${id}`,
  adminProducts: "/admin/products",
  adminProduct: (id: string) => `/admin/products/${id}`,
  adminFeedback: "/admin/feedback",
  adminIssues: "/admin/issues",
  adminIssue: (id: string) => `/admin/issues/${id}`,
  chatConversations: "/chat/conversations",
  chatConversation: (id: string) => `/chat/conversations/${id}`,
  chatMessages: (conversationId: string) =>
    `/chat/conversations/${conversationId}/messages`,
  chatAttachments: (conversationId: string) =>
    `/chat/conversations/${conversationId}/attachments`,
  feedback: "/feedback",
  anomalies: "/analytics/anomalies",
  anomaly: (id: string) => `/analytics/anomalies/${id}`,
  eventsTicket: "/events/ticket",
  recommendations: "/recommendations",
  recommendationFeedback: (id: string) => `/recommendations/${id}/feedback`,
  monthlySummaries: "/analytics/monthly-summaries",
  issues: "/issues",
} as const;
